### ISSUE TITLE
[governance-sdk] TypeError: (0 , superstruct_1.instance) is not a function

### ISSUE THREAD

**Issue by jessupjn** [solana-labs/oyster#538]
Our sdk relies on `getGovernance` from `spl-governance`. When the sdk is imported into our react project I am seeing an error thrown in console:
```
[bpfUpgradeableLoader.ts:12] Uncaught TypeError: (0 , superstruct_3.instance) is not a function
    at Object.../switchboardv2-api/node_modules/@solana/spl-governance/lib/tools/sdk/bpfUpgradeableLoader.js (bpfUpgradeableLoader.ts:12:1)
    at Object.options.factory (react refresh:6:1)
    at __webpack_require__ (bootstrap:24:1)
    at fn (hot module replacement:61:1)
    at Object.../switchboardv2-api/node_modules/@solana/spl-governance/lib/governance/version.js (version.ts:10:1)
    at Object.options.factory (react refresh:6:1)
    at __webpack_require__ (bootstrap:24:1)
    at fn (hot module replacement:61:1)
    at Object.../switchboardv2-api/node_modules/@solana/spl-governance/lib/governance/index.js (index.ts:11:1)
    at Object.options.factory (react refresh:6:1)
```

which corresponds to the `PublicKeyFromString` export:
```
export const PublicKeyFromString = coerce(
  instance(PublicKey),
  string(),
  value => new PublicKey(value),
);
```
Wanted to call this out and see if there was something that I may have missed

**Comment by jessupjn** [comment]
Seems to be an issue in webpack - and is reproducible using the `wallet-adapter` starter repos:
1. I forked the repo under [jessupjn/wallet-adapter](https://github.com/jessupjn/wallet-adapter)
2. Added `@solana/spl-governance` dep to `package/starter/create-react-app-starter` and [printed from it](https://github.com/jessupjn/wallet-adapter/commit/62b381c7d51571973a203790eaf0364bd84c20da).
3. UI breaks with the same error shown above.

**Comment by 0xodia** [comment]
Hey @SebastianBor. I am not in the discord directed by that link. Could you copy and paste the workaround for this issue?

**Comment by badass-commits** [comment]
@SebastianBor Unable to load discord convo. Could you please write workaround here?

**Comment by SebastianBor** [comment]
<img width="920" alt="image" src="https://user-images.githubusercontent.com/5817016/164944539-1ee10df6-e76a-4b61-aa3e-177fbbec42d4.png">
